"""Shared data contracts for Agent and Skill boundaries."""

from __future__ import annotations

from datetime import date, datetime, timezone
from enum import StrEnum
from typing import Any, Generic, TypeVar
from uuid import uuid4

from pydantic import BaseModel, Field, HttpUrl, field_validator, model_validator


DataT = TypeVar("DataT")


class EvidenceSource(StrEnum):
    """Source material used for generated or ranked output."""

    METADATA = "metadata"
    ABSTRACT = "abstract"
    FULL_TEXT = "full_text"


class SkillStatus(StrEnum):
    """Execution status for a Skill result."""

    SUCCESS = "success"
    EMPTY = "empty"
    FALLBACK = "fallback"
    ERROR = "error"


class FeedbackValue(StrEnum):
    """Allowed paper-level feedback values."""

    LIKE = "like"
    DISLIKE = "dislike"


class ExplanationMode(StrEnum):
    """Supported selected-paper explanation modes."""

    METHOD = "method"
    EXPERIMENT = "experiment"
    LIMITATIONS = "limitations"


class SearchMode(StrEnum):
    """Search breadth requested for arXiv retrieval."""

    STRICT = "strict"
    BROAD = "broad"


class QueryPlannerMode(StrEnum):
    """Requested query-planning strategy."""

    DETERMINISTIC = "deterministic"
    LLM = "llm"
    AUTO = "auto"


class RetrievalCacheStatus(StrEnum):
    """Completeness status for cached retrieval result sets."""

    COMPLETE = "complete"
    PARTIAL = "partial"
    PLANNER_CACHE = "planner_cache"


class Provenance(BaseModel):
    """Where a paper or generated output came from."""

    source: str
    source_url: HttpUrl | None = None
    retrieved_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    query: str | None = None


class RetrievalQuery(BaseModel):
    """Normalized arXiv retrieval inputs."""

    topic: str | None = None
    category: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    start_index: int = Field(default=0, ge=0)
    max_results: int = Field(default=20, ge=1, le=100)
    search_mode: SearchMode = SearchMode.STRICT
    candidate_pool_size: int | None = Field(default=None, ge=1, le=500)
    page_size: int = Field(default=50, ge=1, le=100)
    max_requests: int = Field(default=4, ge=1, le=20)
    query_planner_mode: QueryPlannerMode = QueryPlannerMode.AUTO

    @model_validator(mode="after")
    def validate_date_range(self) -> "RetrievalQuery":
        if self.start_date is not None and self.end_date is not None:
            if self.start_date > self.end_date:
                raise ValueError("start_date must be before or equal to end_date")
        return self

    @property
    def effective_candidate_pool_size(self) -> int:
        """Candidate pool size requested for ranking after retrieval."""

        return self.candidate_pool_size or self.max_results


class RetrievalBudget(BaseModel):
    """Bounded retrieval request budget for a planned search."""

    candidate_pool_size: int = Field(default=100, ge=1, le=500)
    page_size: int = Field(default=50, ge=1, le=100)
    max_requests: int = Field(default=4, ge=1, le=20)


class QueryPlanVariant(BaseModel):
    """One arXiv query variant generated by query planning."""

    label: str
    search_query: str
    sort_by: str = "relevance"
    sort_order: str = "descending"

    @field_validator("label", "search_query", "sort_by", "sort_order")
    @classmethod
    def require_non_blank_text(cls, value: str) -> str:
        normalized = " ".join(value.split())
        if not normalized:
            raise ValueError("query plan variant fields must not be blank")
        return normalized


class QueryPlannerProvenance(BaseModel):
    """How a query plan was produced."""

    requested_mode: QueryPlannerMode
    source: str
    fallback_reason: str | None = None
    model: str | None = None
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @field_validator("source")
    @classmethod
    def require_source(cls, value: str) -> str:
        normalized = " ".join(value.split())
        if not normalized:
            raise ValueError("planner source must not be blank")
        return normalized


class QueryPlan(BaseModel):
    """Bounded, inspectable set of query variants for retrieval."""

    search_mode: SearchMode
    planner: QueryPlannerProvenance
    variants: list[QueryPlanVariant] = Field(min_length=1)
    required_terms: list[str] = Field(default_factory=list)
    optional_terms: list[str] = Field(default_factory=list)
    phrases: list[str] = Field(default_factory=list)
    rationale: str | None = None

    @property
    def variant_count(self) -> int:
        return len(self.variants)


class RetrievalSourceMetadata(BaseModel):
    """Run-scoped source details for one paper in one retrieval result set."""

    variant_label: str
    sort_by: str
    variant_index: int = Field(ge=0)
    position: int = Field(ge=0)
    first_seen_order: int = Field(ge=0)
    query: str | None = None

    @field_validator("variant_label", "sort_by")
    @classmethod
    def require_source_text(cls, value: str) -> str:
        normalized = " ".join(value.split())
        if not normalized:
            raise ValueError("retrieval source metadata fields must not be blank")
        return normalized


class SkillError(BaseModel):
    """Structured error information that can be shown or logged."""

    code: str
    message: str
    retryable: bool = False


class PaperMetadata(BaseModel):
    """Normalized metadata for an arXiv paper."""

    paper_id: str
    title: str
    authors: list[str] = Field(default_factory=list)
    abstract: str | None = None
    categories: list[str] = Field(default_factory=list)
    published_date: date | None = None
    updated_date: date | None = None
    arxiv_url: HttpUrl
    pdf_url: HttpUrl | None = None
    provenance: Provenance

    @model_validator(mode="after")
    def require_meaningful_identity(self) -> "PaperMetadata":
        if not self.paper_id.strip():
            raise ValueError("paper_id must not be blank")
        if not self.title.strip():
            raise ValueError("title must not be blank")
        return self


class RetrievalResultSet(BaseModel):
    """Cached papers and run-scoped metadata for one effective retrieval plan."""

    query: RetrievalQuery
    papers: list[PaperMetadata] = Field(default_factory=list)
    cache_status: RetrievalCacheStatus = RetrievalCacheStatus.COMPLETE
    source_metadata_by_paper_id: dict[str, list[RetrievalSourceMetadata]] = Field(
        default_factory=dict
    )
    retrieved_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    effective_query_key: str


class SeedRecord(BaseModel):
    """One normalized seed contribution for personalization."""

    identity: str
    input_text: str
    input_type: str
    paper_id: str | None = None
    title: str | None = None
    abstract: str | None = None
    paper: PaperMetadata | None = None
    preference_text: str

    @model_validator(mode="after")
    def require_preference_text(self) -> "SeedRecord":
        if not self.identity.strip():
            raise ValueError("seed identity must not be blank")
        if not self.preference_text.strip():
            raise ValueError("seed preference_text must not be blank")
        return self


class SeedPreference(BaseModel):
    """User interest representation built from normalized seed papers."""

    profile_id: str = "default"
    seeds: list[SeedRecord] = Field(default_factory=list)
    preference_text: str
    vector: dict[str, float] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @model_validator(mode="after")
    def require_seed_signal(self) -> "SeedPreference":
        if not self.profile_id.strip():
            raise ValueError("profile_id must not be blank")
        if not self.seeds:
            raise ValueError("seed preference must include at least one seed")
        if not self.preference_text.strip():
            raise ValueError("seed preference_text must not be blank")
        if not self.vector:
            raise ValueError("seed preference vector must not be empty")
        return self


class Recommendation(BaseModel):
    """Ranked recommendation for one paper."""

    paper: PaperMetadata
    rank: int = Field(ge=1)
    score: float
    rationale: str
    evidence_source: EvidenceSource = EvidenceSource.ABSTRACT
    previous_rank: int | None = Field(default=None, ge=1)
    previous_score: float | None = None
    score_delta: float | None = None
    rank_delta: int | None = None


class FeedbackEvent(BaseModel):
    """One like/dislike event tied to a recommendation context."""

    event_id: str = Field(default_factory=lambda: uuid4().hex)
    profile_id: str = "default"
    recommendation_run_id: str | None = None
    paper_id: str
    value: FeedbackValue
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    paper: PaperMetadata | None = None
    note: str | None = None

    @model_validator(mode="after")
    def require_feedback_identity(self) -> "FeedbackEvent":
        if not self.event_id.strip():
            raise ValueError("feedback event_id must not be blank")
        if not self.profile_id.strip():
            raise ValueError("feedback profile_id must not be blank")
        if not self.paper_id.strip():
            raise ValueError("feedback paper_id must not be blank")
        return self

    @field_validator("created_at", mode="after")
    @classmethod
    def normalize_created_at(cls, value: datetime) -> datetime:
        """Normalize feedback timestamps to UTC-aware datetimes."""

        if value.tzinfo is None or value.utcoffset() is None:
            return value.replace(tzinfo=timezone.utc)
        return value.astimezone(timezone.utc)


class PaperBriefingItem(BaseModel):
    """Structured briefing fields extracted for one ranked paper."""

    paper_id: str
    title: str
    rank: int = Field(ge=1)
    score: float
    summary: str
    contributions: list[str] = Field(default_factory=list)
    methods: list[str] = Field(default_factory=list)
    relevance_rationale: str
    evidence_source: EvidenceSource
    provenance: Provenance
    arxiv_url: HttpUrl


class BriefingTableRow(BaseModel):
    """Compact row used by the daily briefing summary table."""

    rank: int = Field(ge=1)
    paper_id: str
    title: str
    score: float
    key_reason: str
    evidence_source: EvidenceSource
    arxiv_url: HttpUrl


class DailyBriefing(BaseModel):
    """Generated daily briefing from ranked papers and extracted metadata."""

    topic: str
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    executive_summary: str
    summary_table: list[BriefingTableRow] = Field(default_factory=list)
    highlighted_paper: PaperBriefingItem | None = None
    items: list[PaperBriefingItem] = Field(default_factory=list)
    evidence_source: EvidenceSource | None = None
    provenance: list[Provenance] = Field(default_factory=list)


class MethodExplanation(BaseModel):
    """Method or framework explanation fields."""

    problem: str
    method_overview: str
    core_workflow: list[str] = Field(default_factory=list)
    inputs_outputs: list[str] = Field(default_factory=list)
    innovation: str


class ExperimentExplanation(BaseModel):
    """Experiment and results explanation fields."""

    datasets: list[str] = Field(default_factory=list)
    baselines: list[str] = Field(default_factory=list)
    metrics: list[str] = Field(default_factory=list)
    experimental_setup: str
    conclusions: list[str] = Field(default_factory=list)


class LimitationsExplanation(BaseModel):
    """Limitations explanation fields."""

    stated_limitations: list[str] = Field(default_factory=list)
    assumptions: list[str] = Field(default_factory=list)
    missing_validation: list[str] = Field(default_factory=list)
    risks: list[str] = Field(default_factory=list)


class PaperDeepExplanation(BaseModel):
    """Mode-specific explanation for one selected paper."""

    paper_id: str
    title: str
    mode: ExplanationMode
    summary: str
    evidence_source: EvidenceSource
    evidence_note: str
    method: MethodExplanation | None = None
    experiment: ExperimentExplanation | None = None
    limitations: LimitationsExplanation | None = None
    provenance: Provenance
    arxiv_url: HttpUrl

    @model_validator(mode="after")
    def validate_mode_shape(self) -> "PaperDeepExplanation":
        expected = {
            ExplanationMode.METHOD: "method",
            ExplanationMode.EXPERIMENT: "experiment",
            ExplanationMode.LIMITATIONS: "limitations",
        }
        active_name = expected[self.mode]
        active_value = getattr(self, active_name)
        if active_value is None:
            raise ValueError(f"{active_name} explanation is required for mode {self.mode!r}")
        for field_name in expected.values():
            if field_name == active_name:
                continue
            if getattr(self, field_name) is not None:
                raise ValueError(
                    f"{field_name} must be omitted for mode {self.mode!r}"
                )
        return self


class SkillResult(BaseModel, Generic[DataT]):
    """Standard result envelope returned by every Skill."""

    status: SkillStatus
    data: DataT | None = None
    evidence_source: EvidenceSource | None = None
    provenance: list[Provenance] = Field(default_factory=list)
    error: SkillError | None = None
    message: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_status_shape(self) -> "SkillResult[DataT]":
        if self.status == SkillStatus.SUCCESS and self.error is not None:
            raise ValueError("successful SkillResult must not include an error")
        if self.status in {SkillStatus.ERROR, SkillStatus.FALLBACK} and self.error is None:
            raise ValueError("error or fallback SkillResult must include an error")
        return self
